### ISSUE TITLE
Windows daemon executable support.

### ISSUE THREAD

**Issue by trissylegs** [kanidm/kanidm#93] opened 2019-09-19 10:12 UTC
Support building and running the daemon as an ordinary Windows Executable file. This would constitute MVP windows support.

Sorry if this is overly explicit. But nearly everything I listed here has caused me some form of pain or curiosity. Fell free to spin off any particulars into new tickets.

Ordinary exes are built for either Console or Win32 runtimes, 
Not as a service (seperate issue), not requiring an .msi installer (just unzip into a directory), not as some COM blackmagic, not as a IIS webapp.
Not a portability workarounds; cygwin, msys2, WSL, Docker, magically installing itself in %AppData%/myRudeProgram (looking at you various electron apps)

Binaries should be signable. This is security software after all. Windows can be configured to only run exes from selected vendors. (eg, set a SQL Server to only run Microsoft binaries and no-one can run MyGoofyRansomware.exe on your server)

Windows has some *fun* issues to deal with.

It should be reasonably simple to run, and not require rustup/cargo to get ahold of a functioning binary. (First time I tried copying a rust binary between windows machines it did not *run*.

What I would consider as necessary to be a well behaved windows binary: 
* Build with Rust Teir-1 windows targets. (msvc and gnu toolchain)
* All tests that aren't `cfg(unix)` must pass.
* Given it's an exe it should support:
  * Launched from cmd.exe and powershell.exe.
  * Launched by double clicking the icon on explorer or start menu.
  * Launched from Windows Scheduler.
  * In some of these it probably needs a default config file to read, and not rely on command line args or environment vars (neither of which are Windows idiomatic). 
* Instructions on how to install the binary.
* It is allowed rely on reading files in the same directory, (Eg dll's, resources, etc)
* It can run from a Readonly directory. (Eg, C:/Program Files/kandimd) (Could we have a build option to make this mandatory)
* For this software it should be runnable as a Network Service user (a locked down User for running network services)
 *It should not rely on use of the windows Registry. (I don't want *uninstalled* binaries touching the resgistry). 

Potential windows issues:
* Entire toolchain is distinct from GNU and LLVM.
* Building *might* involve someone installing Visual Studio.
* PE/2 binaries are more limited than ELF (I'm think of the 2GiB filesize, but there may be others)
* Windows may not have the correct  system libraries. Eg, it mights have MSVC 12 and not 15)
  * (Can be resolved by ensuring the correct Redistributable is installed).
* Command line passing and parsing is different.
* Console exes vs Windows exes.
* ANSI vs Unicode. (All Rust binaires should be Unicode anyway)
* Networking. Windows port binding permissions are very different.

At a minimum support for Windows 10 and Server 2016 (yes 2019 is current, but 2016 is more common)
Ideally support for Windows 7 and 2012. (Until Window 7 is EOL)
Should probably look at running on Windows Server Core. (Stripped down windows server)

**Comment by NiryaAestus** [comment] 2019-09-19 10:15
This turned out longer than I expected for just "clicking on it should work".

I have Visual Studio Enterpise 2019 and access to not one, but two MSDN subscriptions (one is going to end soon-ish I think).  I would like to help and have some useful resources..

**Comment by Firstyear** [comment] 2019-09-19 10:17
This is awesome! I'd highly encourage you to copy-paste this content into designs/windows_support.rst so we have the documentation in the repo outside of just this ticket.

I'm pretty happy for this to be an umbrella issue, and you/we open PR's that address individual parts of the issue over time. Something I'd throw into this list, if we are going to support windows server, we should have it in the CI to be sure (@JJJollyjim added CI support in PR #92, and we are discussing some specifics there). 

The only libraries today that I think are not pure rust would be sqlite3 and openssl. That's probably something to keep in mind as a unix specific part. Everything else is using things like structopt or saving data to sqlite, so really trying to avoid unix specifics. 

Really happy you want to help out on this!

**Comment by NiryaAestus** [comment] 2019-09-19 11:15
I'll do that.
(Currently in my phone)

I'll include other windows support considerations as well.

**Comment by NiryaAestus** [comment] 2019-09-19 14:03
I've managed to build *most* of it. First snag was having openssl installed. I installed it with vcpkg. (For x64-windows). 
Now I've hit a snag on sqlite. Gotta look at how it's being linked. Hopefully it can be just installed with vcpkg as well.

**Comment by Firstyear** [comment] 2019-09-19 14:09
Did you want to add steps to the readme for preparing a windows env based on your experience? Don’t want to miss out on your lessons you’re picking up here :)

William

**Comment by NiryaAestus** [comment] 2019-09-19 14:35
Okay it works with sqlite3 as well.  I've written down the key stumbling blocks. But I want to get the whole quickstart for windows done, which involves getting a self signed cert. (Powershell has command built in which I use a lot.). Gonna catch some Z's now though. 😴

**Comment by JJJollyjim** [comment] 2019-09-19 14:56
If you didn't come across this, `rusqlite` has a `bundled` feature which we could use automatically on windows with the `[target.'cfg(windows)'.dependencies]` syntax in Cargo.toml

**Comment by Firstyear** [comment] 2019-09-19 21:11
OpenSSL is a requirement however as explained in https://github.com/Firstyear/kanidm/pull/98#issuecomment-533308820 . I think it will not be possible to avoid this if we want to have Webauthn support.

**Comment by NiryaAestus** [comment] 2019-09-19 22:52
I'd also like to dynamicly link openssl so it can be rapidly upgraded if a heartbleed scale bug occurs.
Windows 10 and server 2019 increasing have Microsoft provided OpenSSH. I'll check if that's using openssl (as oppose to libre) so Windows update can provide it.

**Comment by NiryaAestus** [comment] 2019-09-20 03:20
Windows OpenSSH is using LibreSSL.  Windows has LibreSSL's libcrypto.dll in C:\Windows\System32.
![image](https://user-images.githubusercontent.com/1563368/65296740-c786ce00-dba8-11e9-950e-b99b354f764f.png)

**Comment by yaleman** [comment] 2022-07-05 01:21
I can confirm that `kanidm` (the CLI) builds on Windows - and is automated https://github.com/kanidm/kanidm/actions/workflows/windows_build.yml

**Comment by yaleman** [comment] 2022-07-05 07:31
Once #903 is merged, kanidmd's also working 😄

**Comment by trissylegs** [comment] 2022-07-09 02:07
Also checked with Windows 11 on ARM64. kanidm CLI works as expected and Tests pass.
Windows has OpenSSH but doesn't support AuthorizedKeysCommand. So that's most of what's possible now.

**Comment by yaleman** [comment] 2022-07-09 02:37
Nice! Thanks for testing!

**Comment by Firstyear** [comment] 2022-07-18 00:14
I think this can be closed then?

**Comment by yaleman** [comment] 2022-07-18 09:14
Looks like it? #905 has been opened to implement the missing file permission checks, there's a few requests in the original issue description that I have no clue about though 😄 

- runnable as a network service  (I haven't got a server install to test it)
- compiled binary signing 

All the other stuff looks to be done.

**Comment by trissylegs** [comment] 2022-07-19 04:45
Network service is mostly a permission thing (there's a special user for network services that that has less privlages).
Compile Binary Signing will require a Fancy EV code signing certificate. Which is a bit more complicated so should be it's own ticket.

**Comment by Firstyear** [comment] 2022-07-20 00:38
For now I think if it costs money, it's not happening. But the other parts are viable, but we probably need an installer/setup of some kind too .... but I think that also needs to be it's own issue, and really depends on demand.

**Comment by yaleman** [comment] 2023-08-16 03:19
See #1906 - closing this.

**Closed by yaleman** 2023-08-16 03:19 UTC
Labels: wontfix
