### ISSUE TITLE
Secret provisioning support (admin / idm_admin passwords, oauth2 basic secret)

### ISSUE THREAD

**Issue by oddlama** [kanidm/kanidm#1747] opened 2023-06-18 14:52 UTC
**Is your feature request related to a problem? Please describe.**

I'm using NixOS to declaratively manage a fleet of servers. I'd like to be able to provision a full kanidm setup (including oauth2 systems and users) from the ground up. While I can determine what changes would have to be applied to a kanidm instance to bring it into a certain state, currently there is not way to realize some of those changes.

One example is that I'd have to be able to set the basic secrets for oauth manually, such that I can provision the oauth client server independent of setting up a new oauth system on kanidm. Since kanidm only lets me retrieve secrets via `kanidm system oauth2 show-basic-secret ...` but not change them, it means I now have to setup kanidm first, and then sync the secret to the other servers. This is a lot of manual work which I would like to avoid, but I haven't found any solution on how I can accomplish this currently without manually editing the DB (which would probably be a bad idea).

Being able to choose the `admin` and `idm_admin` passwords would also help a lot, and there might be other things with similar issues that I didn't interact with yet.

**Describe the solution you'd like**

I would love to have a way to set my own secrets via `kanidm system oauth2 set-basic-secret ...` or a similar command, so I can use nix to generate, manage and store the secrets for me.

**Comment by Firstyear** [comment] 2023-06-18 23:32
The problem is that we don't want people to set their own secrets because they may be insecurely generated, re-used, or any other number of things. So it's unlikely we'll ever open the door to this - I've simply seen too many times where developers hand out a feature going "yes, users will use this properly" only for it to be misused and then blamed on the developers (us) for letting people have the ability to cause themself harm. And even worse, it harms users who didn't consent to their instance admins doing insecure things, causing those users harms.

My goal is to make a secure-by-default service, that can not be mishandled, so that users are not coming into accidental harms.  So as annoying as it may be in your use case, this is a secure-by-default design. 

I *would* consider alternate methods of oauth2 client authentication, but due to the oauth2 rfc ( https://www.rfc-editor.org/rfc/rfc6749#section-2.3 ) only specifying basic auth, then we really can't rely on other external services to implement other oauth2 client authentication types. 

Ultimately your issue comes down to provisioning, and effectively wanting a way that "a root user can use their local access to effect change on the kanidm instance". 

We've had a similar request from #1476 where someone wanted to have an external config management tool direct user entry state. This is problematic for it's own reasons (mainly that users self-changing things will run into the config management tool destroying their updates).

So I think what we need is something a bit in the middle - a way that the root user can trigger the kanidm client to grant it an admin token so that it can perform the enrollment of users to idm_admins group for delegated permissions, and to allow it to check and retrieve the secrets as needed in provisioning.

IMO that's the best way forward here as it grants you the ability to still automate things, but without yielding control of secrets generation and management to untrusted external applications. 

The design of this would need some work and investigation but I think this is the best way to proceed.

**Comment by yaleman** [comment] 2023-06-19 00:37
I put some support in for automation a while back:
- the recover-account flow supports JSON output (`-o json`)
- You can pass that password auth for accounts with password auth using the env var `KANIDM_PASSWORD`.
- The `kanidm` client should support the outputs in JSON format (`-o json`) - and if not then I'm happy to support adding them.

**Comment by oddlama** [comment] 2023-06-19 00:54
> My goal is to make a secure-by-default service, that can not be mishandled, so that users are not coming into accidental harms. So as annoying as it may be in your use case, this is a secure-by-default design.

I fully understand that. Unfortunately (for me) that will probably mean that I can't have fully declarative systems with kanidm. But I guess I can work around that ultimately.

> I _would_ consider alternate methods of oauth2 client authentication, but due to the oauth2 rfc ( https://www.rfc-editor.org/rfc/rfc6749#section-2.3 ) only specifying basic auth, then we really can't rely on other external services to implement other oauth2 client authentication types.

I'm not familiar with any alternative methods that may be out there, are you thinking of ECDSA based schemes? But yes, this won't work anyway if the clients don't support that.

> Ultimately your issue comes down to provisioning, and effectively wanting a way that "a root user can use their local access to effect change on the kanidm instance".

Yes, that would definitely be a great help!

**Comment by yaleman** [comment] 2023-06-20 06:39
> that will probably mean that I can't have fully declarative systems with kanidm. But I guess I can work around that ultimately.

How would credential revocation work in this "declarative" design? Do you have to rebuild the environment from scratch? I'm really trying to understand how there's no scope to accept credentials from one step and push it into other things. 

For context, I come from a cloud/terraform/dynamic systems background and if I tried this with any other auth provider the conversation would end right there.

**Comment by oddlama** [comment] 2023-06-20 11:22
> How would credential revocation work in this "declarative" design?

I'm not sure whether you are referring to user credentials or oauth credentials here. User credentials are aalways runtime state, and not part of the declarative system by design. Oauth credentials on the other hand are not really state, since I know in advance where and how I use them.

The declarative part essentially boils down to the idea that the repository containing a nix configuration (or ansible or whatever) should be entirely self-contained. Changing the oauth secret would just mean changing the secret in the repository and redeploying. On the kanidm instance this would automatically figure out that the secret has changed and execute the necessary commands to bring kanidm into the correct state. On the oauth "client" this would just change the used secret. So you can change both independently of one another (or more likely deploy at the same time).

It would also be declarative if you would setup a credential management server that distributes them automatically via a secure channel to other servers, but this is a complex and security-sensitive mechanism that I would like to avoid if possible. For small to medium installations this just isn't a feasible approach, especially when the alternative is as simple as the above.

Kanidm's current way of forcing you to generate new secrets on the instance forces your other servers to depend on a runtime generated value of the kanidm instance. So after changing it, you manually have to copy that secret over to the configuration repository and re-deploy the client. But this means that the secret stored in the repository is not the source of truth anymore,  but just an additional artifact that has to be tracked.

My point here is that authentication secrets should not be considered state in the same way you might consider user data to be state. Choosing the secret in advance is of course possible in theory and would eliminate the need to track this entirely. But I can understand that kanidm doesn't want to provide a way to configure it insecurely. What I concluded in the sentence you quoted is, that this forces me to give up my pure configuration and move to a two-step process to distribute the secrets.

> Do you have to rebuild the environment from scratch? I'm really trying to understand how there's no scope to accept credentials from one step and push it into other things.

No, I think this is a slight misunderstanding. Nothing prevents you from syncing credentials out-of-band like on any regular system. But you don't *want* to introduce state where you don't have to, and a separate step to distribute secrets is unnecessary in theory (see above). If the system configuration repository is the only source of truth, your deployments have no other dependencies. Ideally, the only dynamic state I want to track is user-data, which is local to any server and means my backups are also self-contained.

> For context, I come from a cloud/terraform/dynamic systems background and if I tried this with any other auth provider the conversation would end right there.

I imagine at that scale you would just have a credential distribution mechanism that doesn't care if the source of truth is a repository or a server running a kanidm instance. This essentially makes oauth credentials an ephemeral secret that you don't care about at all in your configuration. But this is an additional security-sensitive and very complex system, which most people and medium businesses will not have. Since the theoretical alternative here is so simple I would personally avoid it if I don't have to use it for some other reason.

Sorry for the wall of text, I hope I could clear up some of the confusion.

**Comment by Firstyear** [comment] 2023-06-21 00:15
> On the kanidm instance this would automatically figure out that the secret has changed and execute the necessary commands to bring kanidm into the correct state.

This is our conflict here I think.

You want nixos to be the source of state, and then kanidm and the application to reflect that.

Where as we are pushing Kanidm is the source of state and then nixos is responsible to retrieve and reflect that state where needed.

This was chosen because we don't want to *trust* external state in Kanidm. External state brings liabilities because the moment we trust your external state then we also trust *anyone elses* external state. we don't want that because in this project our goal is to raise the bar, to bring things up to a high level of security, and to enforce secure behaviour.

So it's unlikely we'll ever trust external state - but having automated ways to retrieve state and then allow config management tools to propagate that as required is something that I am more interested in. 

As a result, what I'm going to take from this is that we may consider ways to improve our ability to retrieve secrets or state as needed from within the host when acting as a trusted local user.

**Comment by oddlama** [comment] 2023-06-21 01:13
> This was chosen because we don't want to _trust_ external state in Kanidm. External state brings liabilities because the moment we trust your external state then we also trust _anyone elses_ external state. 

I absolutely do understand your position, and I'm fine with it being that way. It's mostly reasonable.

> we don't want that because in this project our goal is to raise the bar, to bring things up to a high level of security, and to enforce secure behaviour.

Have you considered that in some cases you might just be moving the risk and responsibility to other parts of the system as a whole instead of truly avoiding it? By forcing kanidm to be the secret generator, you also force users to come up with privileged access schemes that can automatically move their secrets between hosts. (Because realistically doing this manually is not feasible if you have more than a handful of servers). So people will come up with various solutions, some of them good and some of them bad.

Users can make mistakes in that additional process just as well as they can in choosing bad credentials in kanidm. Worst case, there will be permanent synchronization services with privileged access to the kanidm instance. The difference on paper being that currently all the responsibility is shifted to the external system in use. Whether this will be more or less secure in practice depends on the grand scheme of things.

I guess my point is that you cannot realistically protect the user from making every mistake, but you can try to make it as hard as possible. By allowing to set credentials that have a certain format and entropy you would not necessarily compromise your goal - and might prevent some installations from adding possibly insecure and complex stuff on top. I do understand why you are sticking with your principles, but personally I'm not entirely sold on the fact that this will strictly improve security. As with most things, I believe there's a hidden "cost-benefit curve" here.

But of course, I'm biased.

> So it's unlikely we'll ever trust external state - but having automated ways to retrieve state and then allow config management tools to propagate that as required is something that I am more interested in.
> 
> As a result, what I'm going to take from this is that we may consider ways to improve our ability to retrieve secrets or state as needed from within the host when acting as a trusted local user.

That would definitely be a huge help and I appreciate it.

**Comment by yaleman** [comment] 2023-06-21 02:22
> you also force users to come up with privileged access schemes that can automatically move their secrets between hosts.

This seems strange to call out, since you're asking us to support that exact use case?

**Comment by yaleman** [comment] 2023-06-21 02:22
PR #1758 implements the OAuth2 secret output in JSON, if there's any other commands needed, please feel free to call them out or submit a PR updating the output format for the particular command.

**Comment by yaleman** [comment] 2023-06-27 23:28
Closing this, thanks for raising the discussion!

**Closed by yaleman** 2023-06-27 23:28 UTC
