### ISSUE TITLE
Setting a credential type minimum policy does not invalidate existing credentials of lower type

### ISSUE THREAD

**Issue by tumbl3w33d** [kanidm/kanidm#2575] opened 2024-02-22 13:41 UTC
### I did this

* started a local kani instance
* onboarded myself with a reset link
* created passkey and a passwort+totp credentials
* tried to log in with pw + totp (works as expected)
* `kanidm group account-policy credential-type-minimum idm_all_persons passkey`
* tried to login with my pw + totp

### I expected the following

* to not be able to login with weak credentials anymore
* to at least be able to delete them (UI does not allow it)
  * that would require all affected users to act (not happening)

### Kanidm version details

official rc.16 container

### Any other comments

The UI shows you that these credentials aren't cool anymore but this also keeps you from deleting them. Still, they remain valid. I assume there is a way to delete these credentials from my users manually with a loop or something (input appreciated), but in my view it would make more sense to do that for the operator when they enable such policy. You would at least need to inform the operator that enabling the policy won't be sufficient to keep users from using password + totp.

**Comment by yaleman** [comment] 2024-02-22 14:31
As designed it only blocks it on reset, curious that it blocks *deletion* of them though?

**Comment by tumbl3w33d** [comment] 2024-02-22 14:34
It just won't show them anymore. You just see
```
Alternative Authentication Methods

Account policy prevents you from setting these credentials
```
But I just tried to simply submit the form anyway and it worked and removed them, so it's basically just a UX issue from enduser side, but for the operator there's not easy path to make sure everyone removed their weak credentials.

**Comment by Firstyear** [comment] 2024-02-23 01:01
Duplicate of #2358 

Yes, we do automatically remove them and the UX could be better there. We have some plans in 2358 to improve this a bit because we need to have a grace period between "introduction of the policy" to allow people to add stronger creds, to the point when they are flatly denied from working.

**Closed by Firstyear** 2024-02-23 01:01 UTC

**Comment by tumbl3w33d** [comment] 2024-02-23 01:12
So, until this enforce possibility arrives, do I have a chance to find and delete all users' PW+TOTP and delete them? You say here you delete them but as I said (and your linked issue says) people can still login with them so they effectively exist but are not visible.

**Comment by Firstyear** [comment] 2024-02-23 01:34
They are deleted the next time the user *updates* their credentials. 

If you want to forcefully delete them, that is possible, but it may be gentler to ask your users to delete them themself to start with. I can give you some raw search commands to look for users that still have these accounts if you want to enforce passkey only. It is a shortcoming of the current design, which is why we want to address it in future. The limit is always time, and I only have so much of it.
