### ISSUE TITLE
Allow multiple redirect_uris in oauth2

### ISSUE THREAD

**Issue by Tom-Hubrecht** [kanidm/kanidm#1980] opened 2023-08-14 12:39 UTC
**Is your feature request related to a problem? Please describe.**

This issue is almost the same as https://github.com/kanidm/kanidm/issues/1290 , I am using kanidm as the identity provider for a self-hosted [netbird management server](https://netbird.io). The problem I have is that for the PKCE authorization flow, it uses internal urls : `http://localhost:53000`, but in kanidm the url registered is `https://netbird.example.selfhosted:443`, which is different. Therefore, I cannot setup the mobile client for netbird.

It is possible to change part of the redirect url in the flow to `https://netbird.example.selfhosted:53000`, but the port cannot change as it ~identifies the device trying to connect, and thus the redirect_uri check still fails.

**Describe the solution you'd like**

Reading the previous issue, I see that adding multiple redirect_uris would come with its issues, but would resolve the problem here. I don't know if only comparing part of the uri in https://github.com/kanidm/kanidm/blob/master/server/lib/src/idm/oauth2.rs#L1246-L1254 and leaving out the port would be a solution.

**Comment by yaleman** [comment] 2023-08-14 12:59
I'd try specifying the bare domain - is there any documentation relating to this on their site? 

The [IdP config docs](https://docs.netbird.io/selfhosted/identity-providers) mention nothing of having to set up extra ports/IdP configurations per client device.. and that sounds *very* strange.

**Comment by Tom-Hubrecht** [comment] 2023-08-14 13:34
It seems that only two of their supported idps have a special setup for this : [azure](https://docs.netbird.io/selfhosted/identity-providers#step-2-platform-configurations) and [google cloud](https://docs.netbird.io/selfhosted/identity-providers#step-2-create-o-auth-2-0-credentials) and by default it automatically uses `http://localhost:53000` https://github.com/netbirdio/netbird/blob/main/infrastructure_files/configure.sh#L159-L165

I tried to set the bare domain but it doesn't seem to work, I believe it is because https://docs.rs/url/latest/src/url/origin.rs.html#27 sets `443` as a default port for https urls if none is provided

**Comment by Firstyear** [comment] 2023-08-15 04:52
Generally we can't actually set multiple domains here - we need to know the singular domain to generate correct redirects and validate the redirects we are being sent. We also need to know the correct url for the original redirect from the app-link portal in the webui.

IMO this appears to be a flaw in netbirdio rather than Kanidm here - oauth2 generally indicates you need a single domain for redirects, and there shouldn't be redirects bouncing you to localhost and the proper domain name. So I think you should bring this up to netbirdio to resolve this.

**Comment by yaleman** [comment] 2023-08-15 05:05
[rfc6749 section-3.1.2.2](https://www.rfc-editor.org/rfc/rfc6749#section-3.1.2.2) says the AS MAY allow multiple redirection URLs to be specified 🤔 

We could add an "additional redirection urls" attribute which could be checked, and use the "main" one (set when the RS is configured) as the app link?

Redirecting to `http://localhost/*` is... a concern. 🤮

**Comment by Firstyear** [comment] 2023-08-15 05:18
Hmmmm maybe. I'm still not sure though, it's a very odd/edge case. I think the redirect to localhost for pkce is a big concern.

**Comment by csarn** [comment] 2023-08-25 07:20
But redirect to localhost absolutely necessary for CLI programs, right? I'm thinking of switching to kanidm from authelia/ldap. One of my use cases is using https://github.com/smallstep/cli to update SSH user certificates based on an OIDC login. So my authelia configuration allows a redirect to localhost for this. 
I don't understand enough about OIDC to know how PKCE fits into that picture, though. As a user I just want to be able to continue using CLI tools with OIDC when I switch to kanidm.

**Comment by Firstyear** [comment] 2023-08-27 22:55
PKCE is required so that a client that doesn't have authentication can be "bound" so that the client originating the request is also the one that receives the request. This requires a PKCE verifier to be created on the origin that "starts" the oauth2 workflow, and then the IDM redirects back to the same origin where the verifier can be used with the code exchange to ensure it's the same client.

This is why we need to accept only a single url. Because otherwise it allows token hijacking and other potential attacks to be carried out.

What *should* be occuring is that the OIDC/oauth2 flow is carried out between Kanidm and Smallstep, using only the smallstep redirect urls. Then once complete and smallstep has the token issued, it can provide that to the CLI where it can be verified by the public keys published in the discovery URL.

This is discussed at length in https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics specifically https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#name-redirect-uri-validation-att and https://datatracker.ietf.org/doc/html/draft-ietf-oauth-security-topics#name-authorization-code-injectio 

Note also the oidc nonce does *not protect* against all these attacks, PKCE is required even with the OIDC nonce.

As a result, my suspicion (without investigating further) is that the smallstep flow *may* be insecure.

Hope that helps,

**Comment by Firstyear** [comment] 2023-08-28 22:02
The other alternative of how the flow is done is that the oauth2 flow is done between your machine and kani so the redirects *only* need to go to localhost, then once your machine has the oidc token it can be sent to small step as the resource server, which can then verify the legitimacy of the token with kani. Then smallstep can issue the ssh ca.

Regardless there is no secure situation where you need https://foo.bar and https://localhost in the same flow - the redirects must always go to the same urls.

**Comment by 0xC0ncord** [comment] 2024-01-10 04:03
I'm hitting this exact scenario with my self-hosted Kubernetes cluster but I'm not sure how to proceed based on the information provided here.

So far the Kubernetes API servers are correctly configured with OIDC to Kanidm. The client (me) issues commands to the cluster with a JWT obtained via [kubelogin](https://github.com/int128/kubelogin) which provides a client-side OIDC flow with a redirect URL of http://localhost:8000. The kube-apiserver validates this JWT against Kanidm and performs the action or returns an error if the token is invalid.

I'd like to be able to expose the Kubernetes Dashboard to my local network. This webapp supports authentication by passing an `Authorization` header to it, which is then forwarded to the kube-apiserver. Unfortunately the dashboard webapp does not perform an OIDC login flow of its own and so a tool like [oauth2-proxy](https://github.com/oauth2-proxy/oauth2-proxy) is required.

The problem is now we have 2 redirect URLs, http://localhost:8000 and https://dashboard.example.com.

**Comment by yaleman** [comment] 2024-01-10 04:07
It's in the backlog to do, see also #2390

**Comment by Firstyear** [comment] 2024-01-10 04:08
I'm working on it now too in conjunction with the custom claimm change.

**Comment by Firstyear** [comment] 2024-01-10 04:09
(The reason I'm doing them together is they both need a domain version bump and some migration stuff that's easy to put together :) )

**Comment by Firstyear** [comment] 2024-01-12 07:15
@yaleman isn't this a dupe of #2390 ?

**Comment by yaleman** [comment] 2024-01-12 13:45
Kinda yeah, one's for specifically handling the "localhost" problem, the other's for allowing *multiple* redirects, but if you squint... 😄

**Closed** 2024-01-16 00:44 UTC
Labels: enhancement, oauth2
