### ISSUE TITLE
Don't set default domain_name `example.com`

### ISSUE THREAD

**Issue by erictapen** [kanidm/kanidm#623] opened 2021-11-29 16:31 UTC
Continuing https://github.com/kanidm/kanidm/pull/617#issuecomment-978373115 here.

As I already laid out, I think it's an unintuitive situation that `domain_name` is currently set to `example.com` at first startup and then must be changed by the user. A server that is configured with `example.com` is unusable for every situation (except in integration tests), but pretends to be in a state where everything is configured properly.

From a user side the ideal solution imo would be:

When no `domain_name` is set yet, the server quickly fails, communicating what needs to be done to the user.

```
$ kanidmd server
Creating db...
There is currently no domain_name set. Run `kanidmd domain_name_change` to set one. Also see the docs here blabla
```

~~Also it would be nice to have `kanidmd domain_name_change` create the db at startup if it doesn't exist yet, so it would be optional to run `kanidmd server` first.~~

**Comment by Firstyear** [comment] 2021-11-30 00:28
domain_name_change already DOES create the db at startup :) 

The flag for if the domain name isn't changed "at least once" could be pretty easy to add, so I think this is absolutely solvable :)

**Comment by Firstyear** [comment] 2021-11-30 00:32
Just as an admin note, I'm currently working on adding some final features to oidc at the moment, so I won't be able to work on this for a little, so either remind me in a week or two, or if you want some advice to implement this yourself, I can help out :)

**Comment by erictapen** [comment] 2021-11-30 00:43
> domain_name_change already DOES create the db at startup :)

Cool!

**Comment by MathiasPius** [comment] 2022-01-22 08:22
I just ran into this problem, while trying to set up my first kanidm installation using Docker.

The way I would intuitively expect provisioning to work would be:

1. Configure `server.toml` with `db_path` set, and `origin` set to `idm.mydomain.com` for example.
2. Running kanidm/server with this `server.toml` should initialize a new database with `idm.mydomain.com` as the domain_name, since no pre-configured database exists.

What actually happens is that I get an error message about origin and domain (actually `ed` and `rp_id`) being different, and a reference to the documentation (nice!) which doesn't explain why example.com is configured in the first place (not so nice!), when I'm starting from scratch, as per @erictapen 's original issue.

> domain_name_change already DOES create the db at startup :)
This is correct, but a check fails before `domain_name_change` runs if your origin is set to anything other than the pre-configured domain_name (example.com if starting from scratch), which means that you have to remove your desired origin from your `server.toml` file before running `domain_name_change`.

So this means that the only way I've gotten this to work is to do something like this:

1. Configure a server.toml with only `db_path` configured.
2. Run kanidm/server with `domain_name_change` to rename to `idm.mydomain.com`
3. _Modify_ `server.toml` with the origin I always wanted to use
4. Run kanidm/server using the new `server.toml`

My problem with this flow is that it's not idempotent, which means it's very hard to define a provisioning/deployment flow with something like docker-compose or Kubernetes, which will always do the right thing, i.e.: rename in case of change, no-op if domain already set.

---
I think there are two different solutions:

1. When starting from scratch, assume no domain_name and either:
  a. Derive it from `origin`.
  b. Require it be specified in the `server.toml` like @erictapen suggests.
2. Don't validate `origin == domain_name` when executing `domain_name_change`.

**Option 1a** makes initial setup a bit more magical, which might go against the "Easy to understand" point of the project's stated goal.
**Option 1b** effectively adds another required field to `server.toml` configuration, but...

... Both of those solutions however means that in the majority of kanidm use cases, people would never ever have a reason to run `domain_name_change`, which I think is a huge plus as far as ease of use goes. Subsequent runs of `domain_name_change -n idm.mydomain.com` would be no-ops, succeed quietly.

**Option 2** Means that you could effectively always run `domain_name_change -n idm.mydomain.com` as a precaution whenever you start your container, and your kanidm instance would automatically enter its "desired state".

P.S. I don't mind getting my hands dirty and implementing either of these solutions, but I want to hear if my understanding of the problem is correct first, or if I'm missing an obvious/easier solution.

**Comment by Firstyear** [comment] 2022-01-22 23:26
> 
> 1. When starting from scratch, assume no domain_name and either:
>    a. Derive it from `origin`.
>    b. Require it be specified in the `server.toml` like @erictapen suggests.
> 2. Don't validate `origin == domain_name` when executing `domain_name_change`.

I don't really want people to accidentally step on origin != domain name though, which is the problem. 

> 
> **Option 1a** makes initial setup a bit more magical, which might go against the "Easy to understand" point of the project's stated goal.

There's already a lot of magic you don't see. Easy to understand just means it has to be transparent what the behaviour is and why. 

> **Option 1b** effectively adds another required field to `server.toml` configuration, but...
> 
> ... Both of those solutions however means that in the majority of kanidm use cases, people would never ever have a reason to run `domain_name_change`, which I think is a huge plus as far as ease of use goes. Subsequent runs of `domain_name_change -n idm.mydomain.com` would be no-ops, succeed quietly.
> 
> **Option 2** Means that you could effectively always run `domain_name_change -n idm.mydomain.com` as a precaution whenever you start your container, and your kanidm instance would automatically enter its "desired state".
> 
> P.S. I don't mind getting my hands dirty and implementing either of these solutions, but I want to hear if my understanding of the problem is correct first, or if I'm missing an obvious/easier solution.

Generally all of this get's into webauthn stuff pretty quick, because it's the problem area in this matter. Webauthn requires that rp_id must be the effective domain of origin. 

we always have to think - "what are properties of the system as a whole" IE the collection of replicas that make up kanidm, and "what are properties of the individual server". 

Option 1b is a non-starter. If two servers in a replication group have different domain names, this will create an infinite replication loop. domain name is a property of the system and must be specified in the database so that replication can correctly manage that. 

Option 2 is also a no-go - origin HAS to gel with the domain name, else webauthn will break.

Option 1a is interesting, but I think it can be expanded on for me to accept it :) 

So let's assume first run - we start up and in the server domain settings entry, we check if the "first_run" flag (* actually, a setup step flag with an int ...) has been set. If it has NOT been set, then we can take origin and make that the domain name. I think line 2272 of src/lib/server.rs is probably where that would need to go, but we'd need to give the origin into that part of the server setup too. 

Then second. domain_name_change is modified so that instead of taking `-n` as an argument, we extract origin as the domain name we intend to use. We can keep -n as an "override" if you want a subdomain of origin as the domain name. 

The main issue I see here is just passing origin to `.initialise_helper` from our config. 

This way:

1. An admin on first run only has to set origin, and we derive domain name from that *once*
2. An admin can change origin and restart and still be warned if it's invalid as a change.
3. An admin can change origin and run domain_name_change and it will be picked up into the database.
4. An admin can run domain_name_change manually to set a subdomain of origin and it's still validated.

How does that sound?

**Comment by Firstyear** [comment] 2022-01-22 23:27
PS: this starts to touch realllllyyyy close to https://github.com/kanidm/kanidm/issues/62 which has been a long standing "desire" for me to do some re-architecture and cleanup. In this case I think you can go ahead and make the change if you want, and I'll look to do the QS cleanup sooner than later to make this kind of thing a bit nicer.

**Comment by yaleman** [comment] 2022-01-23 00:50
> Option 1b is a non-starter. If two servers in a replication group have different domain names, this will create an infinite replication loop. domain name is a property of the system and must be specified in the database so that replication can correctly manage that.

I'd argue that replication shouldn't even start between two servers/clusters that had different domain names if this was going to be the outcome... there should be some kind of bootstrap check that says "hi, am I even *allowed* to do this, and are we going to torch each other?"

Otherwise you'd get into that situation I've been in with certain network switches where you plug two together and the "recipient" shoves a blank/terrible configuration over your intended "source" device.

**Comment by Firstyear** [comment] 2022-01-23 01:25
> > Option 1b is a non-starter. If two servers in a replication group have different domain names, this will create an infinite replication loop. domain name is a property of the system and must be specified in the database so that replication can correctly manage that.
> 
> I'd argue that replication shouldn't even start between two servers/clusters that had different domain names if this was going to be the outcome... there should be some kind of bootstrap check that says "hi, am I even _allowed_ to do this, and are we going to torch each other?"
> 
> Otherwise you'd get into that situation I've been in with certain network switches where you plug two together and the "recipient" shoves a blank/terrible configuration over your intended "source" device.

Yes that's true, but then if the setting is a property of the cluster, then it should be managed "in that cluster" rather than relying on all the server.tomls to be consistent over each individual node I think.

**Comment by MathiasPius** [comment] 2022-01-23 11:19
> Option 1b is a non-starter. If two servers in a replication group have different domain names, this will create an infinite replication loop. domain name is a property of the system and must be specified in the database so that replication can correctly manage that.

I had honestly neglected to consider replication, that's a very good point.

> Option 2 is also a no-go - origin HAS to gel with the domain name, else webauthn will break.

My point here would be to disregard the `domain_name` from the database state and instead complete the `domain_name_change`, and validate the `-n` parameter from that command as the "real" `domain_name`. This way you're still validating that (assuming successful completion of the change), the system will be in a correct state where `origin` from `server.toml` will match `domain_name` from the `domain_name_change` command. 

And obviously if system's `domain_name` matches the parameter to `domain_name_change`, then it's a no-op.

> Option 1a is interesting, but I think it can be expanded on for me to accept it :)
> 
> Then second. domain_name_change is modified so that instead of taking `-n` as an argument, we extract origin as the domain name we intend to use. We can keep -n as an "override" if you want a subdomain of origin as the domain name.
> 
> The main issue I see here is just passing origin to `.initialise_helper` from our config.
> 
> This way:
> 
>     1. An admin on first run only has to set origin, and we derive domain name from that _once_
> 
>     2. An admin can change origin and restart and still be warned if it's invalid as a change.
> 
>     3. An admin can change origin and run domain_name_change and it will be picked up into the database.
> 
>     4. An admin can run domain_name_change manually to set a subdomain of origin and it's still validated.
> 
> How does that sound?

I think that's also a very decent solution. 

I have some concerns regarding the the `server.toml`/database configuration split, like you said earlier about properties of systems vs. properties of nodes...

---
Is the origin a property of each node, or one of the system as a whole?

If it's the property of each node, then it sounds kind of backwards to derive a domain name from it, but if it's a property of the system as a whole, then it also seems misleaading to have it defined in each `server.toml` individually. 

Should origin perhaps be database-managed state like `domain_name` seems to be?

If both are properties of the system as a whole, then perhaps it makes more sense to provide these values as bootstrap arguments to the process, either through the server.toml, by naming them something like `initial_domain` or something, which implies that the value is ignored for subsequent executions against an established system.

Alternatively, it could be done in a way similar to the way `etcd` does it, by having a command-line argument of `--initial-cluster <node1>,<node2>,<node3>`. I'm thinking something like this:
```
kanidmd server --initial-origin https://idm.myexample.com --initial-domain myexample.com
```
By renaming the values the values and/or moving them into the command-line rather than the config file, you avoid the case of someone making changes to `server.toml` and expecting the changes to take effect upon restart.

Also, pardon any ignorance regarding the implications of webauthn origins and domain name changes on my part, my experience from this side of IDM is pretty limited.

**Comment by Firstyear** [comment] 2022-01-24 01:35
> > The main issue I see here is just passing origin to `.initialise_helper` from our config.
> > This way:
> > ```
> > 1. An admin on first run only has to set origin, and we derive domain name from that _once_
> > 
> > 2. An admin can change origin and restart and still be warned if it's invalid as a change.
> > 
> > 3. An admin can change origin and run domain_name_change and it will be picked up into the database.
> > 
> > 4. An admin can run domain_name_change manually to set a subdomain of origin and it's still validated.
> > ```
> > 

> 
> I think that's also a very decent solution.
> 
> I have some concerns regarding the the `server.toml`/database configuration split, like you said earlier about properties of systems vs. properties of nodes...
> 
> Is the origin a property of each node, or one of the system as a whole?
> 
> If it's the property of each node, then it sounds kind of backwards to derive a domain name from it, but if it's a property of the system as a whole, then it also seems misleaading to have it defined in each `server.toml` individually.
> 
> Should origin perhaps be database-managed state like `domain_name` seems to be?

Origin is per node. Domain name is the system as a whole. 

It's valid to have https://idm.example.com and https://remote.idm.example.com. Both are members of "idm.example.com", but have different origins. If the origin, the *exact* url (proto scheme, domain name and port) that the browser accesses the server on is not the exact same as what is sent in webauthn, it fails. That's why we have to have origin as a per-node property, but domain_name is system wide because domain_name becomes the relying party id, and that relates to some credentials in how they validate themself, and if they can be used across other nodes. The relying party id must be the effective domain of the origin, and so that's why it has to be idm.example.com here because then it's a valid domain component to both remote.idm.example.com and idm.example.com. 

This is also before we get to resident keys, which are bound to a relying party ID. See:

https://www.w3.org/TR/webauthn-2/#client-side-discoverable-credential

"""
As a consequence, a discoverable credential capable authenticator can generate an assertion signature for a discoverable credential given only an RP ID, which in turn necessitates that the public key credential source is stored in the authenticator or client platform.
"""

So we need the RP ID to be "stable" and an effective domain of origin, and it binds some credentials to our identity provider, so changing the RP ID is not an option, it has to be consistent over every server in the system. 

This becomes super apparent when you may want to have multiple load balancers or redirections to different servers. For example TXT records to DNS locate the nearest server or server group for example. You wouldn't want say ... your laptop to fail to authenticate to some servers but succeeds on others :) 

> Also, pardon any ignorance regarding the implications of webauthn origins and domain name changes on my part, my experience from this side of IDM is pretty limited.

It's all good, that's what I'm here for :) 

Anyway, I hope that clears up the "fun complexity" of why domain name and origin have to be linked, and

**Comment by MathiasPius** [comment] 2022-01-24 14:49
Thanks that makes a ton of sense!

In that case, does not the `--initial-domain` as a command line argument (for example) make sense?

From what I can gather from the code, the source of `example.com` as the default domain is set by the `Plugin::pre_create_transform` implementation for `Domain`, which in turn is called whenever a `QueryServerWriteTransaction` is constructed, which happens the first time in `.initialise_helper` as you mention above.

Would adding an entry of `initial_domain` to the entries of the `CreateEvent` be a workable solution for this? It could be pre-populated prior to the `pre_create_transform`s are run and then looked up from in there? 

Moving this single configuration value all the way from `setup_qs_idms` -> `.initialise_helper` -> `.initialise_schema_core` seems a little awkward, so I'm sure this is a complete misunderstanding of the relation between all these components.

**Comment by Firstyear** [comment] 2022-01-24 23:30
> Thanks that makes a ton of sense!
> 
> In that case, does not the `--initial-domain` as a command line argument (for example) make sense?
> 
> From what I can gather from the code, the source of `example.com` as the default domain is set by the `Plugin::pre_create_transform` implementation for `Domain`, which in turn is called whenever a `QueryServerWriteTransaction` is constructed, which happens the first time in `.initialise_helper` as you mention above.
> 
> Would adding an entry of `initial_domain` to the entries of the `CreateEvent` be a workable solution for this? It could be pre-populated prior to the `pre_create_transform`s are run and then looked up from in there?

No, createEvent describes any generic "create" that MAY occur, and adding in extra options here seems like the wrong option to handle a bootstrapping case. 

I think the better option would be something similar to what password import does - have a phantom attribute on the domain config entry of initial domain that is populated, and on first run use that if present to set the domain in the domain plugin code. 

> 
> Moving this single configuration value all the way from `setup_qs_idms` -> `.initialise_helper` -> `.initialise_schema_core` seems a little awkward, so I'm sure this is a complete misunderstanding of the relation between all these components.

Bootstrapping a system at startup is hard :) 

There is a lot that has to be shifted down through layers, but honestly, there are config values that go down to the backend code etc. There are parts that naturally just have to be tied together to make certain things work. The point of the initialise_helper is exactly that, to take all those bits and put them together to bring up a full IDM from nothing. So in this case, it's the right place to put it. 

> 
> Finally, if all this is already something you're working thinking about with your plans for the QS/Idm split, and I'm just wasting your time, just let me know :)

Not wasting my time at all :)

**Comment by Firstyear** [comment] 2022-02-13 00:18
So had a chat to @yaleman and we thought about a bunch of the cases. Note a "topology" is a set of nodes in replication for this. 

* Create new topology with a new server - define a new domain name and origin.
* New server joining an existing topology - absorb the existing domain name, and validate origin.
* Existing server in the topology - nothing changing
* Existing server in the topology, change origin - validates origin to domain name
* Existing server in the topology, domain name changes from remote replica - need to decide on a course of action here. 


Mostly what we are talking about here is when we create a new topology to make that easier, but then for some things like nix I think they are trying to define and ensure a state each startup. 

So I think the "right" steps to make this work here are:

* Only validate domain + origin in server mode - otherwise it's a warning only.
* On "first run" derive domain from origin, subsequent changes to domain name need the domain name change tool. 

I think this satisfies the most use cases because then you only need to configure server.toml and start, and it will work otu the correct domain, and if you want to change it later, the server will only fail to start in server mode, allowing you to make the changes etc.

**Comment by yaleman** [comment] 2022-02-13 00:32
So to clean up the entire thread it looks like

- exit(1) on origin/domain mismatch
- add `--check` to `kanidmd server` which checks the configuration is valid, displays it in a parseable way and exit(1) on "we can't start"

**Comment by Firstyear** [comment] 2022-02-13 00:40
Okay, I'm working on a PR for this now.  @erictapen and @Flakebi thank you both for your extreme patience as we discussed this, there are going to be some nice changes in the end here I think :)

**Closed** 2022-02-15 06:17 UTC
