### ISSUE TITLE
Restore from backup an other host not working

### ISSUE THREAD

**Issue by fgma** [kanidm/kanidm#2732] opened 2024-04-30 10:07 UTC
### I did this

1. run kanidm/server:1.2.0-dev using docker on one host
2. let it create an empty database without adding any users at all
3. create a backup using kanidmd database backup
4. create the same setup on a different host
5. try to restore the database from the backup file using kanidmd database restore

-> restore fails

[log.txt](https://github.com/kanidm/kanidm/files/15161682/log.txt)

### I expected the following

Successful restore of all data.

### Kanidm version details

- Output of `kanidm(d) version`: kanidmd 1.2.0-dev
- Are you running it in a container? If so, which image/tag?: kanidm/server:1.2.0-dev
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`): centos 7 and debian 12.5

**Comment by Firstyear** [comment] 2024-05-17 03:45
Reading the log I have an idea about what *might* be causing this, but I want to try to reproduce it first :)

**Comment by Firstyear** [comment] 2024-05-17 04:02
@fgma I'm reviewing this and I can't reproduce. From your log there is an odd behaviour, specifically:

```
b1903ceb-2421-45f3-aac5-36bc934189d7 INFO     ┝━ migrate_18_to_19 [ 958µs | 0.46% ]
b1903ceb-2421-45f3-aac5-36bc934189d7 WARN     │  ┝━ 🚧 [warn]: starting 18 to 19 migration. | event_tag_id: 2
b1903ceb-2421-45f3-aac5-36bc934189d7 WARN     │  ┕━ 🚧 [warn]: Domain level has been temporarily lowered to 2
```

This log message indicates that your backup may be from an older version of the server, rather than from 1.2.0. If the backup is from the same version you should not have these messages. Are you certain it's the correct backup file?

**Comment by fgma** [comment] 2024-05-22 19:32
I just tried to reproduce the issue on a single host to make debugging easier. Doing so with 1.2.1 worked without the issue.

I'm sure I had the failure running 1.2.0 on both systems because it was a new test installation on both systems. I'll try to reproduce it again on the same hosts to see if there is any difference.

**Comment by Firstyear** [comment] 2024-08-23 01:29
We have merged a fix for this.

**Closed** 2024-08-23 01:29 UTC
Labels: bug
