### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by Firstyear** [kanidm/kanidm#969] opened 2022-08-05 01:17 UTC
Currently error messages rely on a lot of trace level context to identify their cause. In production we don't have this, so messages at error or warn level need their context expanded to include:

* What went wrong + Where it went wrong
* Why that caused an error to be thrown.
* What can be done about it.

**Comment by yaleman** [comment] 2023-08-16 05:57
closing duplicate of #1984

**Closed by yaleman** 2023-08-16 05:57 UTC
Labels: uwu
