### ISSUE TITLE
How can I trigger a reload of configuration / TLS certificates ?

### ISSUE THREAD

**Issue by ieugen** [kanidm/kanidm#2570] opened 2024-02-22 01:07 UTC
Hello,

**Is your feature request related to a problem? Please describe.**

I am evaluating kanidm for use in my self hosting infrastructure.
I will use docker swarm (single node). 
I would like to generate certificates using LetsEncrypt. 
I can make the certificates available to kanidm in a volume (local mounted directory ?! ).

How can I tell kanidm that the certificates are updated and it should reload them? 

Can I send a signal like SIGUSR1 ? 
Can I use an API ?!
Does it watch certificates and reloads them on change?

**Describe the solution you'd like**

I would like to copy certificates over the existing ones, replacing them.
I would like to send a signal to kanidm to reload the certificates.
SIGUSR1 or http api would be fine IMO (API will require auth :( ) .
A UNIX socket would also be nice !? 

```
# I will check how I can run this in a swarm setup 
docker kill -s SIGUSR1 kanidmd 
```

It would be nice for the information here to be documented if it's implemented.

**Describe alternatives you've considered**

Stop kanidm and start kanidm process.
This will incur downtime and maybe some auth tokens to be lost ?! 
(if they are not persisted - I don't know how kanidm behaves) 
Also not sure if I can do it with my setup. ?! 

**Additional context**

**Comment by Firstyear** [comment] 2024-02-22 01:10
Duplicate of https://github.com/kanidm/kanidm/issues/1271

Currently you need to restart the server to reload certificates. Restarts are "very fast" so this should not be a serious concern. 

Sessions / Auth tokens will survive a restart so that's not a problem.

if you need high-availability you should consider deploy with replication.

**Closed by Firstyear** 2024-02-22 01:10 UTC

**Comment by Firstyear** [comment] 2024-10-24 03:02
@ieugen https://github.com/kanidm/kanidm/pull/3140
