### ISSUE TITLE
Multiple oauth2_rs_origin URLs

### ISSUE THREAD

**Issue by jsimonetti** [kanidm/kanidm#1290] opened 2022-12-23 11:07 UTC
**Is your feature request related to a problem? Please describe.**
I am using kanidm as IDP for several different domains that each host the same identical application (just under a different domainname). Currently I have to duplicate the application and add a new oauth2 client for each seperate domain because there is a 1-to-1 relation between the client-id and the oauth2_rs_origin URL.

**Describe the solution you'd like**
Is there a specific reason a rs could not have multiple oauth2_rs_origin URL's? If not, it would be nice to be able to add multiple oauth2_rs_origin URL's to a resource server. That way I can use just one application (with 1 oauth2 configuration) behind multiple domains.

**Comment by Firstyear** [comment] 2023-01-05 02:30
Sorry for the long delay on this. Having a look at the oauth rfc and the code, I don't see a reason why we couldn't have multiple origins here. I think it won't be too hard to add either.

**Comment by Firstyear** [comment] 2023-01-10 08:14
@jsimonetti I was thinking to implement this, and I realised there is an outstanding question. What do we do for url's for the app-link pages on the front page? Currently it's "not ambiguous" because we only have a single url, so we can just present that for the user and they can follow that link and everything is happy.

But when we have multiple oauth2 urls, which link do we "present" to the user on the applink page for them to follow? Either we can allow the admin to nominate a "primary" url that would be the one that users follow from the app link page, but it also could be in your case that you have "multiple" different urls due to network views or similar. I'm not sure what the "right" answer is here, because it really depends on "why" you have multiple urls to a single application in the firstplace.

So could you elaborate on why you need multiple urls, so that we can try to design something that is user friendly and works for different use cases?

**Comment by jsimonetti** [comment] 2023-01-11 07:47
Hi, I understand the question.
I did not consider this part, as I don't have a use for the app link page at the moment. I assume setting a 'primary' would suffice.
My usecase is that I have some email virtual hosting where kanidm is the authoritative user store. There is a webmail application running at `webmail.<customerdomain>`. This application is provided (multiple times) to different end users, and as such, different domains.
I hope this makes sense.
Thanks!

**Comment by yaleman** [comment] 2023-01-11 21:24
For the app link thing, a primary would be sensible, or just default to the first one, but that'd need us to support re-ordering. 

I've got a use case for the same thing with internal/external-facing URLs for the same UI.

**Comment by jsimonetti** [comment] 2023-01-11 22:15
Re-ordering also might become finicky. Either marking one url as primary (which is then the only url shown for the app)
or
have each url have a show/hide flag, where you can show multiple urls per app, but only show the ones the administrator wants you to see. This would be the most flexible (I think) but requires a UI modification as opposed to just one (primary) url being shown.

**Comment by yaleman** [comment] 2023-01-11 22:26
yeah, re-ordering is probably the worst of all options 😃

**Comment by Firstyear** [comment] 2023-01-12 01:18
So the problem here with both @yaleman's case and @jsimonetti's case is how we display the urls in the applink portal on the kanidm page. For @yaleman, you can't just pick "one or the other" url if you have internal/external dns names, because you need to know specifically "I want to visit internal" or "I want to visit external". So you still would need two entries for each url.

And for @jsimonetti where you have customer virtual hosting, if you have a "single primary url" the issue is when you pick a primary url say "webmail.customer_A.com" that when someone from site B comes along, they'll follow the URL to the site A and potentially see the wrong customers data, or it'll expose their info or whatever. It just "looks bad" regardless. 

So especially for @jsimonetti's case where you have many customers, having an oauth2 resource server per customer is actually correct, both in terms of failure domains (private keys are per resource server, so exposure of one key won't affect all customers), access control (only members of an allowed group to an ouath2 rs can access it, so site A users can't access site B and vice versa), and the user interface is nicer (if the user goes to the applink page, they'll see a url for their sites webmail, not someone elses). 

So if anything from expanding on your use cases, I think actually that the current model of "single url" is actually correct, because of how it will interact with users. 

> Have each url have a show/hide flag, where you can show multiple urls per app, but only show the ones the administrator wants you to see.

In your case, since you'd have to mark every url as shown to users, then when a user visited the applink page if there were one resource server with a url per customer, then a user would see every customers url listed. We'd then need to apply access controls of "which group gets to see which url", which is an extra layer of complexity.

I think the correct answer, is a resource server per customer here because of what you've said. It keeps access control much simpler and more obvious, it retains kanidm as the broker of authorisation (rather than kanidm just allowing all groups to access an RS and the RS having to do group authorisation).

**Comment by Firstyear** [comment] 2023-01-12 03:32
PS: @jsimonetti I'm quite interested in your use of kanidm here for customer access to webmail, so if you wanted to get in contact with more details about the scale and usage that would be really helpful :)

**Comment by jsimonetti** [comment] 2023-01-12 08:35
My setup is not very big (or special I hope). I do virtual hosting for some small local not-for-profits and friends and family.
It's tiny, for the most part best-effort and fits on a single (though beefy) machine. I don't make money off of this (just to cover costs and I enjoy doing it), but I do try to make it as efficient as possible, hence my request.
I am relatively privacy and security aware, so I am looking at ways to offer central authentication and authorization with otp or hardware token authentication.
I would like to use a real IDP to store all users and provide central authentication and authorization. Right now, there are several (sqlesque) databases that hold user information scattered across various customers and applications.

With regard to the webmail, I host 'vanity' urls for the domains aswell as a generic `webmail.<mydomain>`. The vanity url's are now what is biting me.
I have nginx as reverse proxy in front of everything. Combining `auth_request` with `oauth2-proxy` I managed to create an authentication flow for applications that don't natively support oauth2. Webmail being one of them.
The webmail application is a regular webmail application that is entirely stateless. All data related to the user is stored in imap.
What I have found to be working during my testing is a fan-out, fan-in model. I have one database with accounts for all 'customers' (kanidm). Each user that has the `webmail` role is allowed to use webmail. I have one reverse proxy that acts as the entrypoint for everything. Within nginx I have (amongst others) a webmail virtual server, running the app and a corresponding `oauth2-proxy` instance that has the proper clientid and secret configured.
The webmail application then fans back in to use a single imap and smtp server for mail storage and forwarding.

I have a similar idea for a support portal, where I host one ticketing application, used for all customers. But the same problem as with webmal arises and I would have to duplicate everything (fan-out) for each 'vanity' customer url. 
This duplication for every customer tld (fan-out) makes it both inefficient and puts an administrative burden on me.
The same goes for webdav/nextcloud applications, etc. Everything that could use a vanity url and wouldn't require customer specific configuration would fall in this category.

While I understand what you say above about a dedicated resource server per customer, this would quickly become very inefficient (for me).
I could of course choose not to support vanity urls and host all applications under one brand-less generic domain. However, there is no reason (from a security perspective) why I shouldn't, since it's all the same hardware and everything is shared. 
With that in mind, I also thought of the 'hiding' the entire application in kanidm app pages. Purely so I would not leak information about which customers I host. And even though this isn't really a secret (a quick dns lookup would see everything behind a single ip), it would be confusing to my customers, and their list would also grow with every application I add. I would rather create a customer landing page myself that contains links to each application I host for them, then to rely on kanidm to be that landing page.

I do intend to have a client-id/secret per application. I just didn't count on having to do it per customer as well.
I realise this is a bit of a non-typical use of kanidm and it might not be very well suited for this.

**Comment by yaleman** [comment] 2023-01-12 09:07
It probably wouldn't be a *huge* amount of code to automate the nginx config with a custom ansible provider and pykanidm 🤔

**Comment by jsimonetti** [comment] 2023-01-12 09:16
> It probably wouldn't be a _huge_ amount of code to automate the nginx config with a custom ansible provider and pykanidm 🤔

That thought has crossed my mind also. Unfortunately (in this case) I use nixos for this machine and configure everything declaratively. The missing part here is that kanidm cannot be configured this way, so there is some manual stuff involved. I suppose I could look at creating a nixos module for this that allowed this automation part (using pykanidm), but that would probably be above my skill level. It's also not a huge burden, but I like to keep things as straight forward as possible for me.

**Comment by aanderse** [comment] 2023-01-12 11:47
> Edit: I will still have a look at pykanidm though. The idea of automating the provisioning still is very appealing.

You should! It should be really easy to tell `nginx` to look in "runtime directories" (in the NixOS sense of the word) for additional virtual host files just like any other distro. Don't let the static nature of `nix` good you back here.

**Comment by Firstyear** [comment] 2023-01-12 23:55
> I do intend to have a client-id/secret per application. I just didn't count on having to do it per customer as well. I realise this is a bit of a non-typical use of kanidm and it might not be very well suited for this.

Curiously, Kanidm is actually very suited to this kind of setup. Kanidm is separating things "per domain name" because that's how a lot of browser security works. So from the view of Kanidm each "vanity domain" of an application is it's own security boundary. While they may all be hosted on a single server, that doesn't mean we should treat "each non profit" as sharing a security group, we should still try to isolate them when possible!

Remember also this is just setup cost/time - once the various oauth2rs are configured they will just continue to work. So I think that @yaleman's suggestion to automate this is probably a really good one to assist. The oauth2rs setup process is quite easy IMO compared to other IDP's :) 

In the future since you will need to communicate to each non-profit that "idm.shared.domain" will be trusted, you may also just be able to pivot and get people to login to idm.shared.domain as the front landing page then they can applink to the webmail instance. Which in a way, kind of obliviates the need for a vanity domain for the idm anyway (since that is something Kanidm does not support!)

**Comment by Firstyear** [comment] 2023-02-07 23:00
I'm going to close this for now since I think @jsimonetti has a way to proceed - but it's not off the cards to implement this in the future but would take a lot of thought and time to really get it right.

**Closed by Firstyear** 2023-02-07 23:00 UTC
Labels: enhancement
