### ISSUE TITLE
Enforce MFA via group

### ISSUE THREAD

**Issue by myOmikron** [kanidm/kanidm#2213] opened 2023-10-11 15:12 UTC
Hey,
I looked through all the built-in groups, but didn't found a group to enforce MFA on my clients.
I'd like to experiment with kanidm in a company related context, so I need my clients to either login using passkeys or password + totp.

If there's no such feature yet, do you plan on adding something similiar?

**Comment by Firstyear** [comment] 2023-10-11 22:21
@myOmikron This is a duplicate of #1122 which I'm about to start working on in the coming days.

**Closed by Firstyear** 2023-10-11 22:21 UTC
