### ISSUE TITLE
Should show more precise error message when running ``kanidm-unixd``

### ISSUE THREAD

**Issue by victorcwai** [kanidm/kanidm#444] opened 2021-05-19 10:02 UTC
The following just output `uri (-H) missing, can not proceed`, while it should suggest user to check if `/etc/kanidm/config` file is missing.
```
:~> sudo systemctl status kanidm-unixd
[sudo] password for root: 
● kanidm-unixd.service - Kanidm Local Client Resolver
     Loaded: loaded (/usr/lib/systemd/system/kanidm-unixd.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Wed 2021-05-19 04:52:39 CEST; 6h ago
    Process: 3441 ExecStart=/usr/sbin/kanidm_unixd (code=exited, status=101)
   Main PID: 3441 (code=exited, status=101)
        CPU: 31ms

May 19 04:52:39 localhost.localdomain systemd[1]: Started Kanidm Local Client Resolver.
May 19 04:52:39 localhost.localdomain kanidm_unixd[3441]: uri (-H) missing, can not proceed
May 19 04:52:39 localhost.localdomain kanidm_unixd[3441]: thread 'main' panicked at 'not implemented', kanidm_client/src/lib.rs:254:17
May 19 04:52:39 localhost.localdomain kanidm_unixd[3441]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
May 19 04:52:39 localhost.localdomain systemd[1]: kanidm-unixd.service: Main process exited, code=exited, status=101/n/a
May 19 04:52:39 localhost.localdomain systemd[1]: kanidm-unixd.service: Failed with result 'exit-code'.
```

**Comment by yaleman** [comment] 2021-05-19 10:29
That comes from https://github.com/kanidm/kanidm/blob/9d5296a34b1d9b2169537f2fa9fa1a855d589520/kanidm_client/src/lib.rs#L275 - will need to work on the logging for it.

**Comment by Firstyear** [comment] 2021-05-20 00:37
https://github.com/kanidm/kanidm/blob/9d5296a34b1d9b2169537f2fa9fa1a855d589520/kanidm_client/src/lib.rs#L271

This comment is pretty telling 🤣

**Comment by yaleman** [comment] 2021-05-20 02:38
And the `unimplemented!()` directly after it. :)

**Comment by yaleman** [comment] 2021-05-21 11:22
@victorcwai can you check the current version to see how it looks? #446 made some improvements.

**Comment by victorcwai** [comment] 2021-05-21 13:35
Maybe the missing file config message should be printed or at ERROR level? 
Because I think the kanidm-unixd daemon does not work if the config file is missing. 

I should have pointed out that the above message is what happens when I set up according to https://github.com/kanidm/kanidm/blob/master/kanidm_book/src/pam_and_nsswitch.md but forgot to include `/etc/kanidm/config`.

**Comment by yaleman** [comment] 2021-05-21 14:31
It's currently being printed as an error - `eprintln` - but it probably should cause kanidm-unixd to quit if it can't get a url from the config. I've been wondering today if it's worth merging the configuration files somehow - especially in light of #290

**Comment by victorcwai** [comment] 2021-05-21 15:19
Yeah I meant to say that in the case of running the kanidm-unixd daemon, we should also print missing config file. Because I think we can't pass the uri as an argument in this case (unlike client_tool), so we had to rely on the config file.

**Comment by yaleman** [comment] 2021-05-22 01:07
You're right, I'll update that it needs to be added to the client config - you *should* be able to pass it as an environment variable, given the changes in https://github.com/kanidm/kanidm/pull/438/files#diff-d19d2f3d5395878e008d0fb6aa731c1451955a3064b252c29175467087969e7f 

This is where it's stood up in kanidm_unixd: https://github.com/kanidm/kanidm/blob/master/kanidm_unix_int/src/daemon.rs#L434

Which uses the same code paths.. I think, but I haven't got a test platform with the current build.

**Comment by Firstyear** [comment] 2021-05-22 01:22
Really,  Ithink the issue is that kanidm-client should be reporting it's errors up better rather than attempting to log them itself so the caller can then decide how to handle it.

**Comment by Firstyear** [comment] 2022-10-09 00:16
I think this has been resolved via various improvements to the code base

**Closed by Firstyear** 2022-10-09 00:16 UTC
