### ISSUE TITLE
there is no reactor running, must be called from the context of a Tokio 1.x runtime

### ISSUE THREAD

**Issue by farcaller** [kanidm/kanidm#2910] opened 2024-07-16 20:32 UTC
### I did this

I built kanidm from https://github.com/kanidm/kanidm/pull/2867 and then from 028e7c16940f27015ce26aebcaeb6a039f422a2f

### I expected the following

It would start

### This happened instead

```
Log filter: Info
thread 'main' panicked at /build/kanidm-master-vendor.tar.gz/tonic/src/transport/service/executor.rs:15:9:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
stack backtrace:
   0:     0x560e79dbbe07 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4a5853078ed6ad5e
   1:     0x560e78194fec - core::fmt::write::hcb5164cc0001627e
   2:     0x560e79dbb9fe - std::io::Write::write_fmt::h4f047c3956a46825
   3:     0x560e79dbbb84 - std::sys_common::backtrace::print::h33b76037fd95b2fe
   4:     0x560e79dccc97 - std::panicking::default_hook::{{closure}}::hd7fd2e4913eae4ac
   5:     0x560e79dcc993 - std::panicking::default_hook::h13a9a2eb684db87c
   6:     0x560e79dcd07e - std::panicking::rust_panic_with_hook::hda39260d38680d2a
   7:     0x560e79dbc462 - std::panicking::begin_panic_handler::{{closure}}::h150d47ece314bd47
   8:     0x560e79dbc026 - std::sys_common::backtrace::__rust_end_short_backtrace::hf5ef31e5afaaca81
   9:     0x560e79dccda4 - rust_begin_unwind
  10:     0x560e77fdaed5 - core::panicking::panic_fmt::h9a659e19ee4930b5
  11:     0x560e79ede241 - core::panicking::panic_display::h372d465c5cc5e6a6
  12:     0x560e78073556 - tokio::task::spawn::spawn_inner::panic_cold_display::h19a2dfbd09f4ec32
  13:     0x560e79edf65f - tokio::task::spawn::spawn::h8d1e215a7e62c8cf
  14:     0x560e79e8fa56 - <tonic::transport::service::executor::TokioExec as hyper::rt::Executor<F>>::execute::h5395e8c023ff1245
  15:     0x560e79ee6923 - tonic::transport::channel::Channel::new::h7a220e6bd60e6f90
  16:     0x560e79eb20ed - tonic::transport::channel::endpoint::Endpoint::connect_lazy::h3068749d2c5fc5b2
  17:     0x560e79b8667b - opentelemetry_otlp::span::SpanExporter::new_tonic::h12a3eab358df5c01
  18:     0x560e79b85f46 - opentelemetry_otlp::span::SpanExporterBuilder::build_span_exporter::hd62014bafb63e3be
  19:     0x560e79da9698 - opentelemetry_otlp::span::OtlpTracePipeline::install_batch::h9e26592a57252f49
  20:     0x560e79da027a - sketching::otel::start_logging_pipeline::hf556240b9507213b
  21:     0x560e7856733a - kanidmd::main::h5e7982f9c0788ce0
  22:     0x560e78757fb3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h2260982c12b00434
  23:     0x560e78688bd9 - std::rt::lang_start::{{closure}}::h426a29fe669696a1
  24:     0x560e79db5d15 - std::rt::lang_start_internal::hf4417b67ea9bae52
  25:     0x560e7857f0ec - main
  26:     0x7f31c980b10e - __libc_start_call_main
  27:     0x7f31c980b1c9 - __libc_start_main@@GLIBC_2.34
  28:     0x560e78087f15 - _start
  29:                0x0 - <unknown>
```

### Kanidm version details

- Output of `kanidm(d) version`: commits mentioned above

### Any other comments

This only crashes in runtime if `otel_grpc_url` is specified. Removing it allows kanidm to start with no issues.

**Comment by yaleman** [comment] 2024-07-17 00:57
Duplicate of #2866, someone needs to go in and work out unpicking how the logging/runtime pipeline starts up

**Closed by yaleman** 2024-07-17 00:57 UTC
