### ISSUE TITLE
credential update page doesn't warn about navigating away from page with unsaved changes

### ISSUE THREAD

**Issue by Be-ing** [kanidm/kanidm#3237] opened 2024-11-24 19:55 UTC
### I did this
1. Login
2. Navigate to /ui/update_credentials
3. Make any changes to credentials
4. Click a link to navigate to any other page

### I expected the following
Update credentials page warns about unsaved changes before leaving page or automatically saves changes

### This happened instead
Changes to credentials are not saved

### Kanidm version details

- Output of `kanidm(d) version`: 1.4.2
- Are you running it in a container? If so, which image/tag?: latest
- If not a container, how'd you install it:
- Operating System / Version (On Unix please post the output of `uname -a`): Linux alma-4gb-hel1-2 5.14.0-427.42.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Nov 1 14:58:02 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux

### Any other comments
This also occurs on the reset credentials page.

**Comment by tumbl3w33d** [comment] 2024-11-25 21:29
This appears to be a duplicate of #2504 (even though it was about the old UI). The background explained there might help understand the situation. This has been addressed as much as technically possible.

**Closed as completed** 2024-11-25 22:41 UTC
