### ISSUE TITLE
Suggestion: Small improvements to make user onboarding more clear to laymen

### ISSUE THREAD

**Issue by illode** [kanidm/kanidm#2448] opened 2024-01-23 07:01 UTC
**Is your feature request related to a problem? Please describe.**

The Credential Update / Reset page is a bit unclear to people are familiar with Kanidm / authentication terms (TOTP, Passkeys, etc). As it stands, if I were to create accounts for my friends / family, I would need to preemptively explain a bunch of jargon, whereas ideally I would be able to simply create their account and send the credential setup link and have it be explained there.

**Describe the solution you'd like**
Some of these are totally nitpicky, but since I was already making this issue, I figured I may as well include them. The first three are the main ones.
* Since most people probably have no idea what the terms mean, it might be good to either embed (simplified) explanations, or include links to a site that explains the terms.
* `Password / TOTP` should probably be written `Password + Time-based One Time Password (TOTP) generator` or something along those lines, since people will have no idea what that means.
* It should probably list some examples of OTP apps, e.g. Google Authenticator, FreeOTP, and maybe whatever the Microsoft one is called. Microsoft Authenticator?
* ~~It says `Legacy password paired with other authentication factors.`, but there's only one "other" authentication factor (TOTP). It should probably say `Legacy password paired with TOTP`, or nothing at all since that's implied by the header. Unless you're planning to add more forms of MFA in the future.~~ I see https://github.com/kanidm/kanidm/issues/2417 now, which coincidentally is what I want more than passkeys anyways. Ignore this one.
* `Delete this Insecure Password` should probably just say `Delete insecure password` or `Delete password` , since you can only have one password, the `this` is redundant and implies that there can be multiple passwords somehow.
* At the top of the page, it has the display name + `<account name>@<kanidm domain name>`, e.g. `John Carmack` and `john@kanidm.example.com`. While that makes sense given the context of having multiple separate kanidm instances under different subdomains, it somewhat confusingly looks like an email. Moving the `<account name>` next to the display name might make more sense.
* It might be nice to let the user know how long the authentication for that page lasts. Not really sure about this one, it might encourage them to leave the page open if they how long it lasts.

After writing this, I realized it's kind of confusing in text form, so here is a very rough illustration in screenshot form:
![image](https://github.com/kanidm/kanidm/assets/114271894/3a074411-3922-437f-9828-87a5236f0776)

**Comment by illode** [comment] 2024-01-23 07:06
Also just noticed that the bad password errors don't have spaces:
![image](https://github.com/kanidm/kanidm/assets/114271894/df0171c7-8ac2-4a24-a28b-9a95e3455c31)

**Comment by yaleman** [comment] 2024-01-23 08:33
> Delete this Insecure Password should probably just say Delete insecure password or Delete password , since you can only have one password, the this is redundant and implies that there can be multiple passwords somehow.

There are multiple passwords/text-based credentials possible on an account in Kanidm, so it's valid as it is.

- Primary auth
- POSIX auth
- RADIUS credential

**Comment by yaleman** [comment] 2024-01-23 08:36
> Password / TOTP should probably be written Password + Time-based One Time Password (TOTP) generator or something along those lines, since people will have no idea what that means.

From a UX perspective we're probably best putting the TOTP expansion behind a tooltip or something, adding additional verbiage really isn't going to make it any more clear to most folks. Disabling/discouraging TOTP by default is the recommendation either way, something that'll get enforced by account policy in future.

> It should probably list some examples of OTP apps, e.g. Google Authenticator, FreeOTP, and maybe whatever the Microsoft one is called. Microsoft Authenticator?

These are better off behind a link to documentation, TBH.

**Comment by tumbl3w33d** [comment] 2024-01-23 14:02
I can confirm that we also faced some of these challenges and I created a bit of internal documentation to explain some basics, especially to less technical folks, but even devs are not all into auth stuff. One recurring issue in our case was that we handed out yubikeys to everyone but assumed they would know they need to set a PIN to use them with kani, which was naive, of course. After all, it's a walk on the tightrope for kani, because whatever they do, there's no one-size-fits-all (and missing i18n is a thing). Like in previous discussions, I'd advocate configurable links in appropriate places where you can direct your users to tailored (corporate) documentation.

**Comment by Firstyear** [comment] 2024-01-24 00:21
> 
> **Describe the solution you'd like** Some of these are totally nitpicky, but since I was already making this issue, I figured I may as well include them. The first three are the main ones.

I think a lot of these are very good suggestions - this kind of feedback on user experience is really important to us, since obviously as developers we're deep into this topic all the time, so sometimes we don't see the challenges others face. 

One of the hardest things for us is we aren't really a team of experience web-developers either - Most of us have our backgrounds in server side tech. 

> 
>     * Since most people probably have no idea what the terms mean, it might be good to either embed (simplified) explanations, or include links to a site that explains the terms.

This is a good idea, I think tooltips could be an option here? 

> 
>     * `Password / TOTP` should probably be written `Password + Time-based One Time Password (TOTP) generator` or something along those lines, since people will have no idea what that means.

Yep, that's simple. 

> 
>     * It should probably list some examples of OTP apps, e.g. Google Authenticator, FreeOTP, and maybe whatever the Microsoft one is called. Microsoft Authenticator?

iPhones have it built in as well now as part of their password/keychain. I'm wondering how we can have a good structure to show these options. 

> 
>     * ~It says `Legacy password paired with other authentication factors.`, but there's only one "other" authentication factor (TOTP). It should probably say `Legacy password paired with TOTP`, or nothing at all since that's implied by the header. Unless you're planning to add more forms of MFA in the future.~ I see [PIV/Smartcard Authentication #2417](https://github.com/kanidm/kanidm/issues/2417) now, which coincidentally is what I want more than passkeys anyways. Ignore this one.
> 
>     * `Delete this Insecure Password` should probably just say `Delete insecure password` or `Delete password` , since you can only have one password, the `this` is redundant and implies that there can be multiple passwords somehow.

Funnily, it's the other way around. In the past we had ideas about multiple password + totp pairs and things like that, and overtime we've drifted away from that. So these are legacy hold overs from that. I agree tidying it up would be valuable. 

> 
>     * At the top of the page, it has the display name + `<account name>@<kanidm domain name>`, e.g. `John Carmack` and `john@kanidm.example.com`. While that makes sense given the context of having multiple separate kanidm instances under different subdomains, it somewhat confusingly looks like an email. Moving the `<account name>` next to the display name might make more sense.

Seems reasonable. 

> 
>     * It might be nice to let the user know how long the authentication for that page lasts. Not really sure about this one, it might encourage them to leave the page open if they how long it lasts.

Also very reasonable. 



I think some of these are certainly in the realm of "easy enough for a first time PR" if you want. However some of these like the timer on how long the cred update lasts for is probably something one of us will need to do.

Did you want to submit a PR with some of this? Or did you want to leave it to us?

**Comment by illode** [comment] 2024-01-25 01:53
Sure, I'll try to take a look next week.

**Comment by yaleman** [comment] 2024-02-11 07:54
Can this be closed as #2475 was done?

**Comment by Firstyear** [comment] 2024-02-11 08:17
I'll leave it for @illode to decide as they raised the issue.

**Closed** 2024-02-12 01:43 UTC
Labels: uwu
