### ISSUE TITLE
TOTP registration fails

### ISSUE THREAD

**Issue by cuberoot74088** [kanidm/kanidm#506] opened 2021-06-28 20:58 UTC
Hi,
I am trying to register_totp on a test-account. Webauthn is working already. So I have this starting point:

> $  kanidm account credential status xxx --name xxx     
> uuid: 26xxx76
> claims:
> password: set
> totp: disabled
> backup_code: disabled
> webauthn:
>  * key

and using kanidm version from Jun 27, 1b146bd

If I go for the TOTP, I get this error after sending back my code ...
> Error Completing -> TotpVerifyFailed

What can I do to learn why it failed? It seems like it should work, right?

**Comment by yaleman** [comment] 2021-06-28 23:25
Was this with both apps mentioned in #501? There was a change to kanidm's hashing algorithm in #504 which reduced the hash algorithm from SHA512 to SHA256 which is like to solve the problem.

**Comment by Firstyear** [comment] 2021-06-29 00:59
It could simply be that the time window passed - there is some debounce code in there to handle this but perhaps if you take longer than ~60 seconds to enter the code, it can expire. If you tried again did it work? 

@yaleman There would be an issue registering the token then, rather than in the verification phase.

**Comment by yaleman** [comment] 2021-06-29 01:04
I'm a derp, I meant to include this in the other ticket - the error you get back is a verification fail - so it matches previous reported issues.

```Algorithm: SHA512
Period/Step: 30
Secret: X2DUK2WVY23I2
--------------------------------------------------------------
Enter a TOTP from your authenticator to complete registration:
TOTP: 850994
Error Completing -> TotpVerifyFailed(00000000-60da-7102-0b2d-f27961097c0d, 
TotpSecret { accountname: "yaleman", issuer: "yaleman@<myserver>", 
secret: [190, 135, 69, 106, 213, 198, 182, 141], algo: Sha512, step: 30 })
```

**Comment by Firstyear** [comment] 2021-06-29 01:34
verification failure would indicate wrong secret (unlikely) or timer expiry of the code you entered I think. I added some code to allow "TOTP minus one" so that means any code should be valid for 60 seconds. Did you possibly take longer than that to enter the code?

**Comment by Firstyear** [comment] 2021-06-29 01:35
Alternately, is there a clock sync issue between your server and the client? That would also affect this?

**Comment by yaleman** [comment] 2021-06-29 07:38
My above fail was fixed by moving from Authy to Okta client, but this is @cuberoot74088's thread so I'll wait for him 😆

**Comment by cuberoot74088** [comment] 2021-06-29 10:13
I gave it another try, took me around 25 seconds to scan and input the code ... it still fails verification, but I am really wondering about the time zones here:

> Algorithm: SHA512
> Period/Step: 30
> Secret: 4SHYHGEG7C772
>
> Enter a TOTP from your authenticator to complete registration: 
> TOTP: 461863
> [2021-06-29T09:57:07Z DEBUG kanidm_client::asynchronous] "https://srv/v1/account/chase/_credential/primary"
> [2021-06-29T09:57:07Z DEBUG kanidm_client::asynchronous] opid -> "9b5dd184-2951-45eb-a931-520502a785d8"
> Error Completing -> TotpVerifyFailed(00000000-60da-ee5a-0af3-6b6c5c697178, TotpSecret { accountname: "test", issuer: "test@srv", secret: [228, 143, 131, 152, 134, 248, 191, 253], algo: Sha512, step: 30 })
> 
> $ date
> Di 29. Jun 11:57:20 CEST 2021

This is running on the same machine, the +2 h offset is due to UTC↦CEST, would some parts of the program care about timezones?

this is the `date` in my server container
> docker exec c45d date
> Tue Jun 29 10:09:44 AM UTC 2021

and this on the machine 
> date
> Di 29. Jun 12:09:54 CEST 2021

Is this an issue?

**Comment by Firstyear** [comment] 2021-06-29 10:14
The time should be calculated in UTC on both, so I'm thinking the most likely issue is a timezone one or a clock sync issue at the moment :( I'll review the code to be fully sure, but TOTP in the kanidmd server should be using UTC.

**Comment by cuberoot74088** [comment] 2021-06-29 20:15
The server is using `SystemTime::UNIX_EPOCH`, which is UTC as found in https://github.com/kanidm/kanidm/blob/master/kanidmd/src/lib/credential/totp.rs#L150

I am wondering where and how the time is set for the verification 
https://github.com/kanidm/kanidm/blob/master/kanidmd/src/lib/idm/server.rs#L1683
looks like generated with the VerifyTotpEvent 

... hmm, and as there is no exception ("Error", as far as I see), I assume the problem is in the `totp_step` and the token.verify https://github.com/kanidm/kanidm/blob/master/kanidmd/src/lib/idm/mfareg.rs#L96 dose not produce true here.

Unfortunately I could not spot it, maybe this helps somehow anyway.

**Comment by Firstyear** [comment] 2021-06-30 04:41
Closing as this is now confirmed as a duplicate of #501

**Closed by Firstyear** 2021-06-30 04:41 UTC
